import '@repo/ui/globals.css';
import { GeistSans } from 'geist/font/sans';
import { type Metadata } from 'next';
import {
  ConvexClientProvider,
  HuddleProvider,
  Web3Provider,
} from '~/providers';
import '~/styles/globals.css';
import { TRPCReactProvider } from '~/trpc/react';

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return (
    <html className={GeistSans.variable} lang='en'>
      <body>
        <TRPCReactProvider>
          <ConvexClientProvider>
            <Web3Provider>
              <HuddleProvider>{children}</HuddleProvider>
            </Web3Provider>
          </ConvexClientProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
};

export default RootLayout;
