/* eslint-disable @eslint-community/eslint-comments/disable-enable-pair -- auto generated */

/* eslint-disable @eslint-community/eslint-comments/no-unlimited-disable  -- auto generated */

/* eslint-disable -- auto generated  */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './app/__root';
import { Route as IndexImport } from './app/index';
import { Route as GamesGameIdImport } from './app/games.$gameId';

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const GamesGameIdRoute = GamesGameIdImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/games/$gameId': {
      id: '/games/$gameId';
      path: '/games/$gameId';
      fullPath: '/games/$gameId';
      preLoaderRoute: typeof GamesGameIdImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/games/$gameId': typeof GamesGameIdRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/games/$gameId': typeof GamesGameIdRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/games/$gameId': typeof GamesGameIdRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/games/$gameId';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/games/$gameId';
  id: '__root__' | '/' | '/games/$gameId';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  GamesGameIdRoute: typeof GamesGameIdRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesGameIdRoute: GamesGameIdRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/games/$gameId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/games/$gameId": {
      "filePath": "games.$gameId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
